apiVersion: v1
kind: ReplicationController
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: wardle-server
        image: kube-sample-apiserver-prov-7:latest
        imagePullPolicy: Never
        command: [ "/kube-sample-apiserver", "--etcd-servers=http://localhost:2379" ]
        volumeMounts:
        - name: crdlist-volume
          mountPath: /etc/crdlist
        env:
        - name: KUBEPLUS_PLATFORM_FILE
          value: /etc/crdlist/crds.list
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      volumes:
        - name: crdlist-volume
          configMap:
            name: crdlist
