apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: journal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-pod
  template:
    metadata:
      labels:
        app: journal-pod
    spec:
      containers:
      - name: journal
        image: testprov:24
        imagePullPolicy: Never
        volumeMounts:
        - name: kind-compositions-volume
          mountPath: /etc/kubeprovenance
        env:
        - name: KIND_COMPOSITION_FILE
          value: /etc/kubeprovenance/kind_compositions.yaml
      volumes:
      - name: kind-compositions-volume
        configMap:
          name: kind-compositions-config-map


